/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hesapmakinesi;

/**
 *
 * @author sd
 */
public class FrmHesapMakinesi extends javax.swing.JFrame {

    /**
     * Creates new form FrmHesapMakinesi
     */
    public FrmHesapMakinesi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEkran = new javax.swing.JTextField();
        btn7 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnTopla = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnBol = new javax.swing.JButton();
        btnCarp = new javax.swing.JButton();
        btnCikar = new javax.swing.JButton();
        btnEsittir = new javax.swing.JButton();
        btnNokta = new javax.swing.JButton();
        btnGeri = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSil1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(426, 510));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEkran.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txtEkran, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 360, 60));

        btn7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn7.setText("7");
        btn7.setPreferredSize(new java.awt.Dimension(73, 23));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        getContentPane().add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 60));

        btn4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn4.setText("4");
        btn4.setPreferredSize(new java.awt.Dimension(73, 23));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, 60));

        btn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn1.setText("1");
        btn1.setMaximumSize(new java.awt.Dimension(73, 23));
        btn1.setMinimumSize(new java.awt.Dimension(73, 23));
        btn1.setOpaque(false);
        btn1.setPreferredSize(new java.awt.Dimension(73, 23));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, 60));

        btn8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn8.setText("8");
        btn8.setPreferredSize(new java.awt.Dimension(73, 23));
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        getContentPane().add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, 60));

        btn5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn5.setText("5");
        btn5.setPreferredSize(new java.awt.Dimension(73, 23));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, 60));

        btn0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn0.setText("0");
        btn0.setPreferredSize(new java.awt.Dimension(73, 23));
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        getContentPane().add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, 60));

        btnTopla.setBackground(new java.awt.Color(255, 153, 51));
        btnTopla.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTopla.setText("+");
        btnTopla.setPreferredSize(new java.awt.Dimension(73, 23));
        btnTopla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToplaActionPerformed(evt);
            }
        });
        getContentPane().add(btnTopla, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 80, 60));

        btn6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn6.setText("6");
        btn6.setPreferredSize(new java.awt.Dimension(73, 23));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, 60));

        btn3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn3.setText("3");
        btn3.setPreferredSize(new java.awt.Dimension(73, 23));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, 60));

        btn2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn2.setText("2");
        btn2.setPreferredSize(new java.awt.Dimension(73, 23));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, 60));

        btn9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn9.setText("9");
        btn9.setPreferredSize(new java.awt.Dimension(73, 23));
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        getContentPane().add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, 60));

        btnBol.setBackground(new java.awt.Color(255, 153, 51));
        btnBol.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBol.setText("/");
        btnBol.setPreferredSize(new java.awt.Dimension(73, 23));
        btnBol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBolActionPerformed(evt);
            }
        });
        getContentPane().add(btnBol, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 80, 60));

        btnCarp.setBackground(new java.awt.Color(255, 153, 51));
        btnCarp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCarp.setText("X");
        btnCarp.setPreferredSize(new java.awt.Dimension(73, 23));
        btnCarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarpActionPerformed(evt);
            }
        });
        getContentPane().add(btnCarp, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 80, 60));

        btnCikar.setBackground(new java.awt.Color(255, 153, 51));
        btnCikar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCikar.setText("-");
        btnCikar.setPreferredSize(new java.awt.Dimension(73, 23));
        btnCikar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCikarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCikar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 80, 60));

        btnEsittir.setBackground(new java.awt.Color(255, 153, 51));
        btnEsittir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEsittir.setText("=");
        btnEsittir.setPreferredSize(new java.awt.Dimension(73, 23));
        btnEsittir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsittirActionPerformed(evt);
            }
        });
        getContentPane().add(btnEsittir, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, -1, 60));

        btnNokta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNokta.setText(".");
        btnNokta.setPreferredSize(new java.awt.Dimension(73, 23));
        btnNokta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoktaActionPerformed(evt);
            }
        });
        getContentPane().add(btnNokta, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, -1, 60));

        btnGeri.setBackground(new java.awt.Color(255, 0, 0));
        btnGeri.setText("<<");
        btnGeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeriActionPerformed(evt);
            }
        });
        getContentPane().add(btnGeri, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 80, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Hesap Makinesi");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 220, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        btnSil1.setBackground(new java.awt.Color(255, 0, 0));
        btnSil1.setText("C");
        btnSil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSil1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 80, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        ekranKontrol();
        txtEkran.setText(txtEkran.getText() + "0");
    }//GEN-LAST:event_btn0ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        ekranKontrol();
        txtEkran.setText(txtEkran.getText() + "1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        ekranKontrol();
        txtEkran.setText(txtEkran.getText() + "2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        ekranKontrol();
        txtEkran.setText(txtEkran.getText() + "3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        ekranKontrol();
        txtEkran.setText(txtEkran.getText() + "4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        ekranKontrol();
        txtEkran.setText(txtEkran.getText() + "5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        ekranKontrol();
        txtEkran.setText(txtEkran.getText() + "6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        ekranKontrol();
        txtEkran.setText(txtEkran.getText() + "7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        ekranKontrol();
        txtEkran.setText(txtEkran.getText() + "8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        ekranKontrol();
        txtEkran.setText(txtEkran.getText() + "9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnToplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToplaActionPerformed
        sayi1 = Integer.parseInt(txtEkran.getText());
        txtEkran.setText("+");
        operator = "+";

    }//GEN-LAST:event_btnToplaActionPerformed

    private void btnCikarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCikarActionPerformed
        sayi1 = Integer.parseInt(txtEkran.getText());
        txtEkran.setText("-");
        operator = "-";
    }//GEN-LAST:event_btnCikarActionPerformed

    private void btnCarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarpActionPerformed
        sayi1 = Integer.parseInt(txtEkran.getText());
        txtEkran.setText("x");
        operator = "x";
    }//GEN-LAST:event_btnCarpActionPerformed

    private void btnBolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBolActionPerformed
        sayi1 = Integer.parseInt(txtEkran.getText());
        txtEkran.setText("/");
        operator = "/";
    }//GEN-LAST:event_btnBolActionPerformed


    private void btnEsittirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsittirActionPerformed
        sayi2 = Integer.parseInt(txtEkran.getText());

        this.hesapla(operator);

        if (!operator.equals("/")) {
            txtEkran.setText((int)sonuc + "");
            sayi1 = sayi2;//
            sayi2 = sonuc;// Çıkan sonuç eşittire basılmaya devam ettikçe devam eder.

        } else {
            txtEkran.setText(sonucBolum + "");
            sonucBolum =  sayi1;

        }


    }//GEN-LAST:event_btnEsittirActionPerformed

    private void btnGeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeriActionPerformed
        String geri = null;
        
        if (txtEkran.getText().length() >0) {
           
                StringBuilder geriSayi = new StringBuilder(txtEkran.getText());
                geriSayi.deleteCharAt(txtEkran.getText().length()-1);
                geri = geriSayi.toString();
                txtEkran.setText(geri);
                
        }

    }//GEN-LAST:event_btnGeriActionPerformed

    private void btnNoktaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoktaActionPerformed
        ekranKontrol();
        if (txtEkran.getText().equals("")) {
            txtEkran.setText("0" + ",");
        }
        else if (!txtEkran.getText().contains(",")) {
            txtEkran.setText(txtEkran.getText()+",");
        }
        
    }//GEN-LAST:event_btnNoktaActionPerformed

    private void btnSil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSil1ActionPerformed
        txtEkran.setText("");
    }//GEN-LAST:event_btnSil1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmHesapMakinesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmHesapMakinesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmHesapMakinesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmHesapMakinesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmHesapMakinesi().setVisible(true);
            }
        });
    }

    double sayi1;
    double sayi2;
    double sonuc;
    double sonucBolum;
    String operator;

    public void hesapla(String operator) {

        switch (operator) {
            case "+":
                sonuc = sayi1 + sayi2;
                break;
            case "-":
                sonuc = sayi1 - sayi2;
                break;
            case "x":
                sonuc = sayi1 * sayi2;
                break;
            case "/":
                if (sayi1 % sayi2 != 0) {
                    sonucBolum = sayi1 /  sayi2;
                    
                } else {
                    sonuc = sayi1 / sayi2;
                }
                break;
        }

    }

    public void ekranKontrol() {
        if (txtEkran.getText().equals("+") || txtEkran.getText().equals("-") || txtEkran.getText().equals("x") || txtEkran.getText().equals("/")) {

            txtEkran.setText("");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnBol;
    private javax.swing.JButton btnCarp;
    private javax.swing.JButton btnCikar;
    private javax.swing.JButton btnEsittir;
    private javax.swing.JButton btnGeri;
    private javax.swing.JButton btnNokta;
    private javax.swing.JButton btnSil1;
    private javax.swing.JButton btnTopla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtEkran;
    // End of variables declaration//GEN-END:variables

}
